(function() {var implementors = {};
implementors["extprim"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Add.html\" title=\"trait core::ops::arith::Add\">Add</a>&lt;<a class=\"struct\" href=\"extprim/u128/struct.u128.html\" title=\"struct extprim::u128::u128\">u128</a>&gt; for <a class=\"struct\" href=\"extprim/u128/struct.u128.html\" title=\"struct extprim::u128::u128\">u128</a>",synthetic:false,types:["extprim::u128::u128"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Add.html\" title=\"trait core::ops::arith::Add\">Add</a>&lt;<a class=\"struct\" href=\"extprim/traits/struct.Wrapping.html\" title=\"struct extprim::traits::Wrapping\">Wrapping</a>&lt;<a class=\"struct\" href=\"extprim/u128/struct.u128.html\" title=\"struct extprim::u128::u128\">u128</a>&gt;&gt; for <a class=\"struct\" href=\"extprim/traits/struct.Wrapping.html\" title=\"struct extprim::traits::Wrapping\">Wrapping</a>&lt;<a class=\"struct\" href=\"extprim/u128/struct.u128.html\" title=\"struct extprim::u128::u128\">u128</a>&gt;",synthetic:false,types:["extprim::traits::Wrapping"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Add.html\" title=\"trait core::ops::arith::Add\">Add</a>&lt;<a class=\"struct\" href=\"extprim/i128/struct.i128.html\" title=\"struct extprim::i128::i128\">i128</a>&gt; for <a class=\"struct\" href=\"extprim/i128/struct.i128.html\" title=\"struct extprim::i128::i128\">i128</a>",synthetic:false,types:["extprim::i128::i128"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Add.html\" title=\"trait core::ops::arith::Add\">Add</a>&lt;<a class=\"struct\" href=\"extprim/traits/struct.Wrapping.html\" title=\"struct extprim::traits::Wrapping\">Wrapping</a>&lt;<a class=\"struct\" href=\"extprim/i128/struct.i128.html\" title=\"struct extprim::i128::i128\">i128</a>&gt;&gt; for <a class=\"struct\" href=\"extprim/traits/struct.Wrapping.html\" title=\"struct extprim::traits::Wrapping\">Wrapping</a>&lt;<a class=\"struct\" href=\"extprim/i128/struct.i128.html\" title=\"struct extprim::i128::i128\">i128</a>&gt;",synthetic:false,types:["extprim::traits::Wrapping"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
